default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: gumball

development:
  <<: *default
  database: plugintesting_development

test:
  <<: *default
  database: plugintesting_test

production:
  <<: *default
  database: plugintesting_production
